---
- name: Download go tar ball
  shell: curl -o /tmp/go.tar.gz https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz

- name: Untar the tar ball
  shell: tar -C /usr/local -xzf /tmp/go.tar.gz

- name: Export PATH with Go
  shell: echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile

- name: Source profile
  shell: . /etc/profile
